### ISSUE TITLE
things needs to be considered 

### ISSUE THREAD

**Issue by MMhaidari** [Stephen-Adom/portfolio#11]
# what needs to be changed 
- your code base is looking good 🔥 
- kindly consider using a class selector for styling stand-alone elements instead of an id selector which cannot be overwritten by other selectors and has the highest priority 
- kindly add an extra CSS document for adding breakpoints code 
- kindly consider standard naming classes while writing HTML stand-alone elements

**Comment by Stephen-Adom** [comment]
Completed the issues
