### ISSUE TITLE
Suggestions and acknowledgements

### ISSUE THREAD

**Issue by codedit334** [Stephen-Adom/portfolio#6]
- Make images scale without beeing hidden by @Kaghenimbale
- Add meta tags to show us what the code is about by @Codedit334
- Add anchor tags around the portfolio images by @zunairkhan811
- Everything is perfect by everyone

**Comment by Stephen-Adom** [comment]
@Kaghenimbale, @codedit334 , @zunairkhan811;
Thank you for all your feedback. I appreciate it.

**Comment by Stephen-Adom** [comment]
Suggestions from issues completed
